title: qsj2xn's CS Notes
description: UVA CS Notes by qsj2xn
theme: just-the-docs

url: https://ameimeilia.github.io

baseurl: "/uva-cs-notes"

nav_enabled: true

color_scheme: dark

callouts:
  note:
    title: Note
    color: purple